//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Structure.rc
//
#define IDR_MAINFRAME                   100
#define IDR_CHILDFRAME                  101
#define IDD_CHART                       101
#define IDR_VIEWTOOL                    102
#define IDD_CARTESIAN_GRID              109
#define IDD_EDITGRID                    111
#define IDD_JOINT_RESTRAINT             112
#define IDD_JOINT_LOAD                  113
#define IDD_MEMBER_LOAD                 116
#define IDD_DATABASE                    117
#define IDD_MATERIAL_PROPERTY           118
#define IDD_SECTION_PROPERTY            120
#define IDD_MEMBER_DATA                 121
#define IDD_JOINT_DATA                  122
#define IDD_MEMBER_BREAK                123
#define IDD_ABOUT                       124
#define IDD_DISPLAY                     126
#define IDD_FORCE_DIAGRAM               127
#define IDD_MEMBER_RELEASE              128
#define IDD_REBAR_DATA                  129
#define IDD_JLOCAL_AXIS                 133
#define IDD_RADIAL_GRID                 134
#define IDD_LOADCASE                    137
#define IDD_ANALYSIS                    138
#define IDD_COMBINATION                 139
#define IDD_PASTE                       140
#define IDD_CONSTRAINT                  141
#define IDD_MODALCASE                   144
#define IDD_RESULT                      145
#define IDD_RESPONSECASE                146
#define IDD_ANALYSIS_OPTIONS            147
#define IDD_FUNCTION                    149
#define IDD_RESPONSESPEC                150
#define IDD_SLAB_DISTRIBUTED            151
#define IDD_SLAB_DATA                   152
#define IDD_MLOCAL_AXIS                 153
#define IDD_SELECT_DATABASE             154
#define IDD_GROUP_PROPERTY              155
#define IDD_NEW                         156
#define IDD_NEW_3DFRAME                 157
#define IDD_SYSTEM_ORIGIN               159
#define IDD_STRESS_DIAGRAM              160
#define IDD_NEW_BEAM                    161
#define IDD_NEW_2DTRUSS                 162
#define IDD_NEW_3DTRUSS                 163
#define IDD_ANALYSIS_PROGRESS           164
#define IDD_MISC_OPTIONS                165
#define IDD_FUNCTION_PLOT               166
#define IDD_PLOT_RESULT                 167
#define IDD_ANIMATION                   168
#define IDD_DAMPING                     169
#define IDD_SELECT_LABELS               170
#define IDD_DESIGN_OPTIONS              171
#define IDD_MEMBER_DIVISIONS            172
#define IDD_SLAB_DIVISIONS              173
#define IDD_DESIGN_RESULT               174
#define IDD_TAPERED_SECTION             175
#define IDD_CURVED_MEMBER               176
#define IDR_ANALYSISTOOL                177
#define IDR_DESIGNTOOL                  178
#define IDR_DRAWTOOL                    179
#define IDR_SELECTTOOL                  180
#define IDR_SNAPTOOL                    181
#define IDR_EDITTOOL                    182
#define IDR_ASSIGNTOOL                  186
#define IDD_SELECT_TABLE                194
#define IDD_TABLE_VIEW                  195
#define IDD_NLCASE                      197
#define IDD_BUCKLING                    198
#define IDD_SLAB_DIAGRAMS               199
#define IDD_ASECTION_PROPERTY           201
#define IDD_NEW_SLAB                    202
#define IDD_NEW_WALL                    203
#define IDD_NEW_SHELL                   204
#define IDD_DESIGN_OVERWRITES           205
#define IDD_SECTION_MODIFIERS           215
#define IDD_MEMBER_STRAIN               216
#define IDD_JOINT_REACTIONS             217
#define IDD_COLOR                       218
#define IDC_FX                          1006
#define IDC_FY                          1007
#define IDC_FZ                          1008
#define IDC_MXX                         1009
#define IDC_MYY                         1010
#define IDC_MZZ                         1011
#define IDC_ADD_TO_EXISTING             1012
#define IDC_REPLACE_EXISTING            1013
#define IDC_DELETE_EXISTING             1014
#define IDC_NXGRID                      1015
#define IDC_NYGRID                      1016
#define IDC_NZGRID                      1017
#define IDC_XGRID                       1018
#define IDC_YGRID                       1019
#define IDC_ZGRID                       1020
#define IDC_X                           1021
#define IDC_Y                           1022
#define IDC_Z                           1023
#define IDC_LOCLIST                     1024
#define IDC_LOC                         1025
#define IDC_ADD                         1026
#define IDC_MOVE                        1027
#define IDC_DELETE                      1028
#define IDC_DELETEALL                   1029
#define IDC_NEW                         1030
#define IDC_LOAD1                       1031
#define IDC_LOAD2                       1032
#define IDC_LOAD3                       1033
#define IDC_LOAD4                       1034
#define IDC_DISTANCE1                   1035
#define IDC_DISTANCE2                   1036
#define IDC_DISTANCE3                   1037
#define IDC_DISTANCE4                   1038
#define IDC_UNIFORM                     1039
#define IDC_MATERIAL_LIST               1040
#define IDC_DATA_ADD                    1041
#define IDC_DATA_DELETE                 1042
#define IDC_DATA_MODIFY                 1043
#define IDC_NAME                        1044
#define IDC_DATA_IMPORT                 1044
#define IDC_ELASTICITY                  1045
#define IDC_DATA_EXPORT                 1045
#define IDC_POISON                      1046
#define IDC_UNITWEIGHT                  1047
#define IDC_THERMAL_COEFF               1048
#define IDC_SHEAR_MODULUS               1049
#define IDC_SECTION_LIST                1050
#define IDC_DENSITY                     1051
#define IDC_SECTION_NAME                1052
#define IDC_WIDTH                       1053
#define IDC_HEIGHT                      1054
#define IDC_RADIUS                      1055
#define IDC_EDIT_SECTION                1056
#define IDC_FORCE_LIST                  1057
#define IDC_EDIT_MATERIAL               1058
#define IDC_EDIT_JI                     1059
#define IDC_EDIT_JII                    1060
#define IDC_AREA                        1061
#define IDC_AY                          1062
#define IDC_AZ                          1063
#define IDC_IXX                         1064
#define IDC_IYY                         1065
#define IDC_IZZ                         1066
#define IDC_IX                          1067
#define IDC_IY                          1068
#define IDC_IZ                          1069
#define IDC_ZY                          1073
#define IDC_ZZ                          1074
#define IDC_SY                          1075
#define IDC_SZ                          1076
#define IDC_GLOBAL                      1077
#define IDC_LOCAL                       1078
#define IDC_EDIT_RESTRAINT              1079
#define IDC_DJOINT_RESTRAINT            1100
#define IDC_DMEMBER_LABEL               1101
#define IDC_DMEMBER_SECTION             1102
#define IDC_DSLAB_LABEL                 1103
#define IDC_DMEMBER_MATERIAL            1104
#define IDC_DJOINT_SHOW                 1105
#define IDC_DORIGIN                     1106
#define IDC_DGRID                       1107
#define IDC_DJOINT_LOAD                 1108
#define IDC_DMEMBER_LOAD                1109
#define IDC_APPLY_TO_ALL                1110
#define IDC_DMEMBER_AXIS                1111
#define IDC_FILLDIAGRAM                 1112
#define IDC_EDIT_RELEASE                1113
#define IDC_EDIT_DIVISIONS              1114
#define IDC_NUX                         1115
#define IDC_NUY                         1116
#define IDC_NUZ                         1117
#define IDC_NRX                         1118
#define IDC_NRY                         1119
#define IDC_NRZ                         1120
#define IDC_FUX                         1121
#define IDC_FUY                         1122
#define IDC_FUZ                         1123
#define IDC_FRX                         1124
#define IDC_FRY                         1125
#define IDC_FRZ                         1126
#define IDC_COULMN                      1134
#define IDC_BEAM                        1135
#define IDC_RECTANGULAR                 1136
#define IDC_CIRCULAR                    1137
#define IDC_COVER                       1138
#define IDC_BARSIZE                     1139
#define IDC_NZ                          1140
#define IDC_NY                          1141
#define IDC_TOTAL                       1142
#define IDC_EDIT_REBAR                  1143
#define IDC_DRAWING                     1145
#define IDC_FCK                         1146
#define IDC_FCTK                        1147
#define IDC_FYK                         1148
#define IDC_FYKS                        1149
#define IDC_FTK                         1150
#define IDC_FTKS                        1151
#define IDC_TYPE                        1152
#define IDC_STATE_TYPE                  1153
#define IDC_SYSTEM                      1153
#define IDC_UX                          1159
#define IDC_UY                          1160
#define IDC_UZ                          1161
#define IDC_RX                          1162
#define IDC_RY                          1163
#define IDC_RZ                          1164
#define IDC_DATA_LIST                   1166
#define IDC_LOADCASE                    1167
#define IDC_RUN                         1168
#define IDC_LIST                        1169
#define IDC_DJOINT_AXIS                 1170
#define IDC_LIST2                       1170
#define IDC_DSLAB_SECTION               1171
#define IDC_DSLAB_MATERIAL              1172
#define IDC_DSLAB_LOAD                  1173
#define IDC_DSLAB_AXIS                  1174
#define IDC_FS                          1175
#define IDC_CHANGEACTION                1176
#define IDC_STATUS                      1177
#define IDC_ACTION                      1178
#define IDC_SWM                         1179
#define IDC_RUBCURSOR                   1180
#define IDC_DCONSTRAINT                 1181
#define IDC_DNUMBERING                  1182
#define IDC_MIN                         1184
#define IDC_MAX                         1185
#define IDC_MODE                        1185
#define IDC_MODALCASE                   1186
#define IDC_FM                          1187
#define IDC_FK                          1188
#define IDC_W1                          1189
#define IDC_E1                          1190
#define IDC_W2                          1191
#define IDC_FIXED                       1192
#define IDC_E2                          1192
#define IDC_PINNED                      1193
#define IDC_CALCULATE                   1193
#define IDC_EDIT_AXIS                   1194
#define IDC_BREAKN                      1195
#define IDC_PERIODIC                    1195
#define IDC_ROLLER                      1196
#define IDC_TRANSIENT                   1196
#define IDC_BREAKR                      1197
#define IDC_N                           1197
#define IDC_FREE                        1198
#define IDC_PERIOD                      1198
#define IDC_DJOINT_LABEL                1199
#define IDC_STEP                        1199
#define IDC_AMPLITUDE                   1200
#define IDC_EX                          1201
#define IDC_EY                          1202
#define IDC_LX                          1203
#define IDC_LY                          1204
#define IDC_CYCLES                      1205
#define IDC_SCALE                       1206
#define IDC_DIVISIONS                   1207
#define IDC_FUNCTION                    1208
#define IDC_FRAMEDIV                    1208
#define IDC_MODAL                       1209
#define IDC_DIRECTINT                   1210
#define IDC_AG                          1211
#define IDC_SOILTYPE                    1212
#define IDC_DIR                         1213
#define IDC_ABSSUM                      1214
#define IDC_SRSS                        1215
#define IDC_CQC                         1216
#define IDC_DIRABSSUM                   1217
#define IDC_DIRSRSS                     1218
#define IDC_LISTFUNCTION                1219
#define IDC_LISTSCALE                   1220
#define IDC_LISTDIR                     1221
#define IDC_CHART                       1222
#define IDC_UP                          1223
#define IDC_DOWN                        1224
#define IDC_SURFACE                     1225
#define IDC_UNIAXIAL                    1226
#define IDC_BIAXIAL                     1227
#define IDC_INDEX                       1228
#define IDC_CURRENT                     1229
#define IDC_JLIST                       1230
#define IDC_MLIST                       1231
#define IDC_SLIST                       1232
#define IDC_BLANK                       1233
#define IDC_GRID                        1234
#define IDC_BEAM2D                      1235
#define IDC_PLANETRUSS                  1236
#define IDC_SPACETRUSS                  1237
#define IDC_PLANEFRAME                  1238
#define IDC_SPACEFRAME                  1239
#define IDC_SLAB                        1240
#define IDC_SHELL                       1242
#define IDC_PLANEGRID                   1243
#define IDC_NSTOREY                     1244
#define IDC_SHEIGHT                     1245
#define IDC_NBAYY                       1246
#define IDC_BWIDTHY                     1247
#define IDC_NBAYX                       1248
#define IDC_BWIDTHX                     1249
#define IDC_ORIGIN                      1250
#define IDC_MIDX                        1251
#define IDC_MIDY                        1252
#define IDC_RESTRAINT                   1253
#define IDC_ITEM_DIRECTION              1254
#define IDC_SHEAR                       1256
#define IDC_SHEAR_VALUE                 1257
#define IDC_MOMENT                      1258
#define IDC_MOMENT_VALUE                1259
#define IDC_DEFLECTION                  1260
#define IDC_DEFLECTION_VALUE            1261
#define IDC_SECTION                     1262
#define IDC_SCROLL                      1263
#define IDC_SHOWVALUE                   1264
#define IDC_NSPAN                       1265
#define IDC_SPANLENGTH                  1266
#define IDC_NDIV                        1267
#define IDC_DIVLENGTH                   1268
#define IDC_L1                          1269
#define IDC_L2                          1270
#define IDC_N1                          1271
#define IDC_N2                          1272
#define IDC_H1                          1273
#define IDC_H2                          1274
#define IDC_H3                          1275
#define IDC_COVER1                      1276
#define IDC_COVER2                      1277
#define IDC_GAPWIDTH                    1278
#define IDC_GAPTEXT                     1279
#define IDC_TH                          1280
#define IDC_TW                          1281
#define IDC_TAH                         1282
#define IDC_TAW                         1283
#define IDC_LISTTH                      1284
#define IDC_LISTTW                      1285
#define IDC_LISTTAH                     1286
#define IDC_LISTTAW                     1287
#define IDC_SPANX                       1289
#define IDC_SPANY                       1290
#define IDC_NDIVX                       1291
#define IDC_NDIVY                       1292
#define IDC_TOWERTYPE                   1293
#define IDC_BTIME                       1295
#define IDC_ETIME                       1296
#define IDC_ELAPSED                     1297
#define IDC_FILE                        1301
#define IDC_BROWSE                      1302
#define IDC_FORCE                       1305
#define IDC_LOAD                        1306
#define IDC_DISPLAY                     1309
#define IDC_FUNCTION_VALUE              1310
#define IDC_TIME                        1315
#define IDC_SOUND                       1316
#define IDC_FASTER                      1318
#define IDC_SLOWER                      1319
#define IDC_REDO                        1321
#define IDC_CONSTANT                    1323
#define IDC_DAMPING                     1324
#define IDC_INC                         1330
#define IDC_SELECT                      1331
#define IDC_DESELECT                    1332
#define IDC_SINGLE_SHEAR                1334
#define IDC_BAR_LIST                    1335
#define IDC_SHEAR_LIST                  1336
#define IDC_BEAM_LIST                   1337
#define IDC_COLUMN_LIST                 1338
#define IDC_SLAB_LIST                   1339
#define IDC_CUT                         1341
#define IDC_LAYERS                      1342
#define IDC_SPACING                     1343
#define IDC_MEMBER                      1348
#define IDC_DEXTRUDE                    1350
#define IDC_START                       1351
#define IDC_END                         1352
#define IDC_EIYY                        1353
#define IDC_BDIST                       1353
#define IDC_EIZZ                        1354
#define IDC_DIVATINTERIM                1362
#define IDC_SINGLE                      1363
#define IDC_LOADDIR                     1364
#define IDC_MOMENTTYPE                  1366
#define IDC_FORCETYPE                   1367
#define IDC_TABLE                       1371
#define IDC_CONSTRAINT                  1377
#define IDC_SHIFT                       1380
#define IDC_TOLERANCE                   1381
#define IDC_ABSOLUTE                    1382
#define IDC_RELATIVE                    1383
#define IDC_NSTEPS                      1384
#define IDC_NITERATION                  1385
#define IDC_STIFFNESS                   1386
#define IDC_SELECT_CASES                1393
#define IDC_DMEMBER_RELEASE             1395
#define IDC_NMODES                      1396
#define IDC_DIVX                        1401
#define IDC_DIVY                        1402
#define IDC_AVERAGE                     1420
#define IDC_STRESS                      1425
#define IDC_SHEARWALL                   1427
#define IDC_NANGULAR                    1428
#define IDC_OVERWRITES                  1430
#define IDC_JPOINT                      1435
#define IDC_OPTIONS                     1437
#define IDC_ES                          1438
#define IDC_SBARSIZE                    1439
#define IDC_SET_MODIFIERS               1440
#define IDC_EDITSS                      1442
#define IDC_EDITES                      1443
#define IDC_SOFFSET                     1444
#define IDC_EOFFSET                     1445
#define IDC_VALUE                       1452
#define IDC_LIST1                       1454
#define IDC_LIST3                       1455
#define IDM_SELECT                      39000
#define IDM_ADD_JOINT                   39001
#define IDM_ADD_MEMBER                  39002
#define IDM_ADD_CURVED_MEMBER           39003
#define IDM_ADD_RECT_AREA               39004
#define IDM_ADD_QUAD_AREA               39005
#define IDM_QUICK_DRAW_MEMBER           39006
#define IDM_LINE_SELECT                 39007
#define IDM_ONE_WINDOWS                 39010
#define IDM_TWO_WINDOWS                 39011
#define IDM_THREE_WINDOWS               39012
#define IDM_FOUR_WINDOWS                39013
#define IDM_MOVEVIEWUP                  40010
#define IDM_MOVEVIEWDOWN                40011
#define IDM_RUN_ANALYSIS                40012
#define IDM_RUBBERZOOM                  40013
#define IDM_RESTOREVIEW                 40014
#define IDM_ZOOMIN                      40015
#define IDM_ZOOMOUT                     40016
#define IDM_PAN                         40017
#define IDM_JOINT_RESTRAINT             40018
#define IDM_JOINT_CONSTRAINT            40019
#define IDM_JOINT_CONSTRAINTX           40020
#define IDM_JOINT_CONSTRAINTY           40021
#define IDM_JOINT_CONSTRAINTZ           40022
#define IDM_JOINT_FORCE                 40023
#define IDM_JOINT_DISPLACEMENT          40024
#define IDM_JOINT_MASS                  40025
#define IDM_JOINT_AXIS                  40026
#define IDM_MEMBER_SECTION              40027
#define IDM_MEMBER_POINT                40028
#define IDM_MEMBER_DISTRIBUTED          40029
#define IDM_MEMBER_STRAIN               40030
#define IDM_MEMBER_AXIS                 40031
#define IDM_MEMBER_JOIN                 40032
#define IDM_MEMBER_BREAK                40033
#define IDM_MEMBER_RELEASE              40034
#define IDM_SELECT_ALL_JOINTS           40035
#define IDM_SELECT_ALL_MEMBERS          40036
#define IDM_SELECT_ALL_SLABS            40037
#define IDM_SELECT_ALL                  40038
#define IDM_DESELECT_ALL_JOINTS         40039
#define IDM_DESELECT_ALL_MEMBERS        40040
#define IDM_DESELECT_ALL_SLABS          40041
#define IDM_DESELECT_ALL                40042
#define IDM_INVERT_SELECTION            40043
#define IDM_DEFINE_MATERIAL             40044
#define IDM_DEFINE_FRAME_SECTION        40045
#define IDM_DISPLAY_OPTIONS             40046
#define IDM_DIAGRAMS                    40047
#define IDM_DEFLECTED                   40048
#define IDM_DISPLACEMENT                40049
#define IDM_REACTIONS                   40050
#define IDM_SHOW_LOADS                  40051
#define IDM_SHOW_RESULT                 40052
#define IDM_DESIGN                      40053
#define IDM_DESIGN_SELECTED             40054
#define IDM_SHOW_DESIGN_RESULT          40055
#define IDM_SYSTEM                      40056
#define IDM_RIGHT                       40057
#define IDM_LEFT                        40058
#define IDM_UP                          40059
#define IDM_DOWN                        40060
#define IDM_LOAD_CASE                   40061
#define IDM_LOAD_COMBO                  40062
#define IDM_COPY                        40063
#define IDM_CUT                         40064
#define IDM_PASTE                       40065
#define IDM_DELETE                      40066
#define IDM_SHOWGRIDS                   40067
#define IDM_SHOWORIGIN                  40068
#define IDM_REFRESH                     40069
#define IDM_CONSTRAINT                  40070
#define IDM_MODAL_CASE                  40071
#define IDM_RESPONSE_CASE               40072
#define IDM_ANALYSIS_OPTIONS            40073
#define IDM_TIME_HISTORY_FUNC           40074
#define IDM_RESPONSE_SPECTRUM           40075
#define IDM_SPECTRUM_FUNC               40076
#define IDM_SLAB_SECTION                40077
#define IDM_SLAB_AXIS                   40078
#define IDM_SLAB_REVERSE_AXIS           40079
#define IDM_SLAB_DIVISIONS              40080
#define IDM_SLAB_JOIN                   40081
#define IDM_SLAB_BREAK                  40082
#define IDM_SLAB_DISTRIBUTED            40083
#define IDM_SLAB_STRAIN                 40084
#define IDM_PREPARE_DRAWING             40085
#define IDM_PREPARE_DRAWING_SELECTED    40086
#define IDM_SELECT_SECTION              40087
#define IDM_DESELECT_SECTION            40088
#define IDM_SELECT_CONSTRAINT           40089
#define IDM_DESELECT_CONSTRAINT         40090
#define IDM_GROUP                       40091
#define IDM_ASSIGN_GROUP                40092
#define IDM_SELECT_GROUP                40093
#define IDM_DESELECT_GROUP              40094
#define IDM_SELECT_LOADCASE             40095
#define IDM_MISC_OPTIONS                40097
#define IDM_PLOT_FUNCTIONS              40098
#define IDM_ANIMATE                     40099
#define IDM_SELECT_FROM_ALL             40100
#define IDM_SELECT_LABELS               40101
#define IDM_DESELECT_LABELS             40102
#define IDM_DESIGN_OPTIONS              40103
#define IDM_DESIGN_VERIFY               40104
#define IDM_MEMBER_DIVISIONS            40109
#define IDM_TAPERED_SECTION             40110
#define IDM_RESET_TOOLBARS              40114
#define IDM_MAINTOOL                    40116
#define IDM_ANALYSISTOOL                40117
#define IDM_DESIGNTOOL                  40118
#define IDM_DRAWTOOL                    40119
#define IDM_SELECTTOOL                  40120
#define IDM_VIEWTOOL                    40121
#define IDM_SNAPTOOL                    40122
#define IDM_EDITTOOL                    40123
#define IDM_ASSIGNTOOL                  40126
#define IDM_SHOW_TABLES                 40136
#define IDM_IMPORT_EXCEL                40137
#define IDM_IMPORT_ACCESS               40138
#define IDM_IMPORT_AUTOCAD              40139
#define IDM_EXPORT_EXCEL                40140
#define IDM_EXPORT_ACCESS               40141
#define IDM_EXPORT_AUTOCAD              40142
#define IDM_UNDO                        40144
#define IDM_REDO                        40145
#define IDM_NONLINEAR_CASE              40147
#define IDM_BUCKLING                    40150
#define IDM_SLAB_DIAGRAMS               40152
#define IDM_DEFINE_SLAB_SECTION         40154
#define IDM_SELECT_ASECTION             40155
#define IDM_DESELECT_ASECTION           40156
#define IDM_DESIGN_COMBOS               40157
#define IDM_PERSPECTIVE                 40158
#define IDM_COLORS                      40162
#define ID_PLACE_HOLDER                 40259
#define ID_COORDINATE                   40260
#define ID_DOCUMENT_LOCK                40261
#define ID_ENTER                        40262
#define ID_ESCAPE                       40263
#define ID_DELETE                       40264
#define ID_VIEW_XY                      40265
#define ID_VIEW_XZ                      40266
#define ID_VIEW_YZ                      40267
#define ID_VIEW_3D                      40268
#define ID_SNAP_TO_GRID                 40269
#define ID_SNAP_TO_JOINT                40270
#define ID_SNAP_TO_MEMBERMID            40271
#define ID_SNAP_MEMBER                  40272
#define ID_SNAP_TO_MEMBER               40273

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         40163
#define _APS_NEXT_CONTROL_VALUE         1456
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
